
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum BattleStatus
    {
        /// <summary>
        /// 战斗中
        /// </summary>
        BattleFight = 103,

        /// <summary>
        /// 战斗结束
        /// </summary>
        BattleEnd = 104,

    }
}
