
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class BOneItem : Bonus
    {
        public BOneItem(ByteBuf buf) : base(buf) 
        {
            itemId = buf.ReadInt();

            PostInit();
        }

        public static BOneItem DeserializeBOneItem(ByteBuf buf)
        {
            return new BOneItem(buf);
        }

        /// <summary>
        /// 物品id
        /// </summary>
        public readonly int itemId;

        public const int Id = -595516425;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "itemId:" + itemId + ","
            + "}";
        }

        partial void PostInit();
    }
}
