
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class BOneItems : Bonus
    {
        public BOneItems(ByteBuf buf) : base(buf) 
        {
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);itemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = buf.ReadInt(); itemIds.Add(_e0);}}

            PostInit();
        }

        public static BOneItems DeserializeBOneItems(ByteBuf buf)
        {
            return new BOneItems(buf);
        }

        /// <summary>
        /// 物品列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> itemIds;

        public const int Id = -1281139876;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "itemIds:" + Luban.StringUtil.CollectionToString(itemIds) + ","
            + "}";
        }

        partial void PostInit();
    }
}
