
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public abstract partial class Bonus : BeanBase
    {
        public Bonus(ByteBuf buf)
        {

            PostInit();
        }

        public static Bonus DeserializeBonus(ByteBuf buf)
        {
            switch (buf.ReadInt())
            {
                case BOneItem.Id: return new BOneItem(buf);
                case BOneItems.Id: return new BOneItems(buf);
                case BCurrency.Id: return new BCurrency(buf);
                case BItemList.Id: return new BItemList(buf);
                case BWeightItem.Id: return new BWeightItem(buf);
                case BProbItem.Id: return new BProbItem(buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
