
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class BProbItem : Bonus
    {
        public BProbItem(ByteBuf buf) : base(buf) 
        {
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);itemList = new System.Collections.Generic.List<DProbItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DProbItem _e0;  _e0 = DProbItem.DeserializeDProbItem(buf); itemList.Add(_e0);}}

            PostInit();
        }

        public static BProbItem DeserializeBProbItem(ByteBuf buf)
        {
            return new BProbItem(buf);
        }

        /// <summary>
        /// 物品列表
        /// </summary>
        public readonly System.Collections.Generic.List<DProbItem> itemList;

        public const int Id = 24830570;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "itemList:" + Luban.StringUtil.CollectionToString(itemList) + ","
            + "}";
        }

        partial void PostInit();
    }
}
