
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class BuildModConfig : BeanBase
    {
        public BuildModConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            name = buf.ReadString();
            description = buf.ReadString();
            type = buf.ReadInt();
            subtype = buf.ReadInt();
            carrierType = buf.ReadInt();
            carrierId = buf.ReadInt();

            PostInit();
        }

        public static BuildModConfig DeserializeBuildModConfig(ByteBuf buf)
        {
            return new BuildModConfig(buf);
        }

        /// <summary>
        /// 模组ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 模组名称
        /// </summary>
        public readonly string name;

        /// <summary>
        /// 模组描述
        /// </summary>
        public readonly string description;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly int type;

        /// <summary>
        /// 二级类型
        /// </summary>
        public readonly int subtype;

        /// <summary>
        /// 载体类型
        /// </summary>
        public readonly int carrierType;

        /// <summary>
        /// 载体ID
        /// </summary>
        public readonly int carrierId;

        public const int Id = 1742982710;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "name:" + name + ","
            + "description:" + description + ","
            + "type:" + type + ","
            + "subtype:" + subtype + ","
            + "carrierType:" + carrierType + ","
            + "carrierId:" + carrierId + ","
            + "}";
        }

        partial void PostInit();
    }
}
