
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum CardType
    {
        /// <summary>
        /// 建筑
        /// </summary>
        House = 1,

        /// <summary>
        /// 强化
        /// </summary>
        Power = 2,

        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 3,

    }
}
