
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class CondReward : BeanBase
    {
        public CondReward(ByteBuf buf)
        {
            condId = buf.ReadInt();
            rewardId = buf.ReadInt();

            PostInit();
        }

        public static CondReward DeserializeCondReward(ByteBuf buf)
        {
            return new CondReward(buf);
        }

        /// <summary>
        /// 条件id
        /// </summary>
        public readonly int condId;

        /// <summary>
        /// 奖励id
        /// </summary>
        public readonly int rewardId;

        public const int Id = 390685969;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "condId:" + condId + ","
            + "rewardId:" + rewardId + ","
            + "}";
        }

        partial void PostInit();
    }
}
