
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class ConstantConfig : BeanBase
    {
        public ConstantConfig(ByteBuf buf)
        {
            version = buf.ReadString();
            batchGetMailMaxNum = buf.ReadInt();
            batchReadMailMaxNum = buf.ReadInt();
            batchReceiveMailMaxNum = buf.ReadInt();
            batchDeleteMailMaxNum = buf.ReadInt();
            mailMaxNum = buf.ReadInt();
            mailExpireSec = buf.ReadInt();
            bagFullMailid = buf.ReadInt();
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);INITITEMLIST = new System.Collections.Generic.List<DItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DItem _e0;  _e0 = DItem.DeserializeDItem(buf); INITITEMLIST.Add(_e0);}}
            ENERGYRECOVERINTERVAL = buf.ReadInt();
            ENERGYRECOVERPOINTS = buf.ReadInt();

            PostInit();
        }

        public static ConstantConfig DeserializeConstantConfig(ByteBuf buf)
        {
            return new ConstantConfig(buf);
        }

        /// <summary>
        /// 版本号
        /// </summary>
        public readonly string version;

        /// <summary>
        /// 批量获取邮件最大数量
        /// </summary>
        public readonly int batchGetMailMaxNum;

        /// <summary>
        /// 批量读取邮件最大数量
        /// </summary>
        public readonly int batchReadMailMaxNum;

        /// <summary>
        /// 批量领取邮件最大数量
        /// </summary>
        public readonly int batchReceiveMailMaxNum;

        /// <summary>
        /// 批量删除邮件最大数量
        /// </summary>
        public readonly int batchDeleteMailMaxNum;

        /// <summary>
        /// 邮件最大数量
        /// </summary>
        public readonly int mailMaxNum;

        /// <summary>
        /// 邮件过期时间
        /// </summary>
        public readonly int mailExpireSec;

        /// <summary>
        /// 背包满邮件id
        /// </summary>
        public readonly int bagFullMailid;

        /// <summary>
        /// 初始物品列表
        /// </summary>
        public readonly System.Collections.Generic.List<DItem> INITITEMLIST;

        /// <summary>
        /// 体力恢复间隔秒
        /// </summary>
        public readonly int ENERGYRECOVERINTERVAL;

        /// <summary>
        /// 体力恢复点数
        /// </summary>
        public readonly int ENERGYRECOVERPOINTS;

        public const int Id = -1411722202;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "version:" + version + ","
            + "batchGetMailMaxNum:" + batchGetMailMaxNum + ","
            + "batchReadMailMaxNum:" + batchReadMailMaxNum + ","
            + "batchReceiveMailMaxNum:" + batchReceiveMailMaxNum + ","
            + "batchDeleteMailMaxNum:" + batchDeleteMailMaxNum + ","
            + "mailMaxNum:" + mailMaxNum + ","
            + "mailExpireSec:" + mailExpireSec + ","
            + "bagFullMailid:" + bagFullMailid + ","
            + "INITITEMLIST:" + Luban.StringUtil.CollectionToString(INITITEMLIST) + ","
            + "ENERGYRECOVERINTERVAL:" + ENERGYRECOVERINTERVAL + ","
            + "ENERGYRECOVERPOINTS:" + ENERGYRECOVERPOINTS + ","
            + "}";
        }

        partial void PostInit();
    }
}
