
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class DItem : BeanBase
    {
        public DItem(ByteBuf buf)
        {
            itemId = buf.ReadInt();
            itemNum = buf.ReadInt();

            PostInit();
        }

        public static DItem DeserializeDItem(ByteBuf buf)
        {
            return new DItem(buf);
        }

        /// <summary>
        /// 物品id
        /// </summary>
        public readonly int itemId;

        /// <summary>
        /// 物品数量
        /// </summary>
        public readonly int itemNum;

        public const int Id = 65088887;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "itemId:" + itemId + ","
            + "itemNum:" + itemNum + ","
            + "}";
        }

        partial void PostInit();
    }
}
