
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class DWeightItem : BeanBase
    {
        public DWeightItem(ByteBuf buf)
        {
            itemId = buf.ReadInt();
            itemNum = buf.ReadInt();
            weight = buf.ReadInt();

            PostInit();
        }

        public static DWeightItem DeserializeDWeightItem(ByteBuf buf)
        {
            return new DWeightItem(buf);
        }

        /// <summary>
        /// 物品id
        /// </summary>
        public readonly int itemId;

        /// <summary>
        /// 物品数量
        /// </summary>
        public readonly int itemNum;

        /// <summary>
        /// 权重
        /// </summary>
        public readonly int weight;

        public const int Id = -1397781233;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "itemId:" + itemId + ","
            + "itemNum:" + itemNum + ","
            + "weight:" + weight + ","
            + "}";
        }

        partial void PostInit();
    }
}
