
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum ErrorCode
    {
        /// <summary>
        /// 参数错误
        /// </summary>
        ParamError = 1,

        /// <summary>
        /// 流程错误
        /// </summary>
        ProcedureError = 10005,

        /// <summary>
        /// 手卡未放完
        /// </summary>
        NotFinishHandCard = 20001,

        /// <summary>
        /// 选卡未结束
        /// </summary>
        NotFinishSelectedCard = 20002,

        /// <summary>
        /// 抽卡未结束
        /// </summary>
        NotFinishDrawCard = 20003,

    }
}
