
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum FuncCondType
    {
        /// <summary>
        /// 解锁功能
        /// </summary>
        HaveUnlockedFunc = 1,

        /// <summary>
        /// 达到vip等级
        /// </summary>
        NeedVipLevel = 2,

    }
}
