
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class FuncOpenConfig : BeanBase
    {
        public FuncOpenConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            funcType = (FuncType)buf.ReadInt();
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);unlockCondIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = buf.ReadInt(); unlockCondIds.Add(_e0);}}

            PostInit();
        }

        public static FuncOpenConfig DeserializeFuncOpenConfig(ByteBuf buf)
        {
            return new FuncOpenConfig(buf);
        }

        /// <summary>
        /// 条件id
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 功能类型
        /// </summary>
        public readonly FuncType funcType;

        /// <summary>
        /// 解锁条件
        /// </summary>
        public readonly System.Collections.Generic.List<int> unlockCondIds;

        public const int Id = 391142448;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "funcType:" + funcType + ","
            + "unlockCondIds:" + Luban.StringUtil.CollectionToString(unlockCondIds) + ","
            + "}";
        }

        partial void PostInit();
    }
}
