
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum FuncType
    {
        /// <summary>
        /// 研究所
        /// </summary>
        ResearchHall = 1,

        /// <summary>
        /// 食堂
        /// </summary>
        MessHall = 2,

    }
}
