
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum HouseType
    {
        /// <summary>
        /// 主城
        /// </summary>
        Castle = 0,

        /// <summary>
        /// 炮塔
        /// </summary>
        Tower = 1,

        /// <summary>
        /// 兵营
        /// </summary>
        Camp = 2,

    }
}
