
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class HouseFashionConfig : BeanBase
    {
        public HouseFashionConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            name = buf.ReadString();
            description = buf.ReadString();
            resourceId = buf.ReadInt();

            PostInit();
        }

        public static HouseFashionConfig DeserializeHouseFashionConfig(ByteBuf buf)
        {
            return new HouseFashionConfig(buf);
        }

        /// <summary>
        /// 房屋时装ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 房屋时装名称
        /// </summary>
        public readonly string name;

        /// <summary>
        /// 房屋时装描述
        /// </summary>
        public readonly string description;

        /// <summary>
        /// 模型资源ID
        /// </summary>
        public readonly int resourceId;

        /// <summary>
        /// 模型资源ID
        /// </summary>
        public ResourceConfig ResourceConfig => ResourceConfigTable.Instance.GetOrDefault(resourceId);

        public const int Id = 627448826;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "name:" + name + ","
            + "description:" + description + ","
            + "resourceId:" + resourceId + ","
            + "}";
        }

        partial void PostInit();
    }
}
