
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum ItemSubType
    {
        /// <summary>
        /// 无
        /// </summary>
        Base = 0,

        /// <summary>
        /// 钻石
        /// </summary>
        Diamond = 1,

        /// <summary>
        /// 金币
        /// </summary>
        Gold = 2,

    }
}
