
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum ItemType
    {
        /// <summary>
        /// 普通物品
        /// </summary>
        Common = 0,

        /// <summary>
        /// 货币
        /// </summary>
        Coin = 1,

        /// <summary>
        /// 物品
        /// </summary>
        Item = 2,

    }
}
