
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class MailConfig : BeanBase
    {
        public MailConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            title = buf.ReadString();
            priority = buf.ReadInt();
            sender = buf.ReadString();
            content = buf.ReadString();
            argsCount = buf.ReadInt();

            PostInit();
        }

        public static MailConfig DeserializeMailConfig(ByteBuf buf)
        {
            return new MailConfig(buf);
        }

        /// <summary>
        /// 邮件id
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 标题
        /// </summary>
        public readonly string title;

        /// <summary>
        /// 优先级
        /// </summary>
        public readonly int priority;

        /// <summary>
        /// 发送者
        /// </summary>
        public readonly string sender;

        /// <summary>
        /// 内容
        /// </summary>
        public readonly string content;

        /// <summary>
        /// 参数数量
        /// </summary>
        public readonly int argsCount;

        public const int Id = 220589049;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "title:" + title + ","
            + "priority:" + priority + ","
            + "sender:" + sender + ","
            + "content:" + content + ","
            + "argsCount:" + argsCount + ","
            + "}";
        }

        partial void PostInit();
    }
}
