
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class MonsterRoundsConfig : BeanBase
    {
        public MonsterRoundsConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            desc = buf.ReadString();
            round = buf.ReadInt();
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);monsterGroupList = new System.Collections.Generic.List<MonsterGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MonsterGroup _e0;  _e0 = MonsterGroup.DeserializeMonsterGroup(buf); monsterGroupList.Add(_e0);}}

            PostInit();
        }

        public static MonsterRoundsConfig DeserializeMonsterRoundsConfig(ByteBuf buf)
        {
            return new MonsterRoundsConfig(buf);
        }

        /// <summary>
        /// 主线关卡回合ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 关卡回合描述
        /// </summary>
        public readonly string desc;

        /// <summary>
        /// 回合
        /// </summary>
        public readonly int round;

        /// <summary>
        /// 怪物组列表
        /// </summary>
        public readonly System.Collections.Generic.List<MonsterGroup> monsterGroupList;

        public const int Id = 1348046113;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "desc:" + desc + ","
            + "round:" + round + ","
            + "monsterGroupList:" + Luban.StringUtil.CollectionToString(monsterGroupList) + ","
            + "}";
        }

        partial void PostInit();
    }
}
