
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class MonsterGroup : BeanBase
    {
        public MonsterGroup(ByteBuf buf)
        {
            groupId = buf.ReadInt();
            positionId = buf.ReadInt();
            spawnTime = buf.ReadInt();

            PostInit();
        }

        public static MonsterGroup DeserializeMonsterGroup(ByteBuf buf)
        {
            return new MonsterGroup(buf);
        }

        /// <summary>
        /// 组id
        /// </summary>
        public readonly int groupId;

        /// <summary>
        /// 位置id
        /// </summary>
        public readonly int positionId;

        /// <summary>
        /// 出生开始时间
        /// </summary>
        public readonly int spawnTime;

        public const int Id = 694741733;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "groupId:" + groupId + ","
            + "positionId:" + positionId + ","
            + "spawnTime:" + spawnTime + ","
            + "}";
        }

        partial void PostInit();
    }
}
