
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class MonsterGroupsConfig : BeanBase
    {
        public MonsterGroupsConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            {int n0 = System.Math.Min(buf.ReadSize(), buf.Size);monsterIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = buf.ReadInt(); monsterIds.Add(_e0);}}
            monsterTotal = buf.ReadInt();
            spawnDelay = buf.ReadInt();
            onceSpawnNum = buf.ReadInt();

            PostInit();
        }

        public static MonsterGroupsConfig DeserializeMonsterGroupsConfig(ByteBuf buf)
        {
            return new MonsterGroupsConfig(buf);
        }

        /// <summary>
        /// 怪物组id
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 怪物id列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> monsterIds;

        /// <summary>
        /// 本组怪物总数
        /// </summary>
        public readonly int monsterTotal;

        /// <summary>
        /// 刷怪间隔(毫秒)
        /// </summary>
        public readonly int spawnDelay;

        /// <summary>
        /// 单次刷怪数量
        /// </summary>
        public readonly int onceSpawnNum;

        public const int Id = -317061360;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "monsterIds:" + Luban.StringUtil.CollectionToString(monsterIds) + ","
            + "monsterTotal:" + monsterTotal + ","
            + "spawnDelay:" + spawnDelay + ","
            + "onceSpawnNum:" + onceSpawnNum + ","
            + "}";
        }

        partial void PostInit();
    }
}
