
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class MonsterAIConfig : BeanBase
    {
        public MonsterAIConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            radius = buf.ReadFloat();
            height = buf.ReadFloat();
            moveSpeed = buf.ReadFloat();
            detectRadius = buf.ReadFloat();
            attackRadius = buf.ReadFloat();
            isPriorityAttackRangeTarget = buf.ReadBool();
            isPriorityAttackAirTarget = buf.ReadBool();

            PostInit();
        }

        public static MonsterAIConfig DeserializeMonsterAIConfig(ByteBuf buf)
        {
            return new MonsterAIConfig(buf);
        }

        /// <summary>
        /// 怪物AI标识ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 体位半径
        /// </summary>
        public readonly float radius;

        /// <summary>
        /// 模型高度
        /// </summary>
        public readonly float height;

        /// <summary>
        /// 移动速度
        /// </summary>
        public readonly float moveSpeed;

        /// <summary>
        /// 探测半径
        /// </summary>
        public readonly float detectRadius;

        /// <summary>
        /// 攻击半径
        /// </summary>
        public readonly float attackRadius;

        /// <summary>
        /// 是否优先攻击远程目标
        /// </summary>
        public readonly bool isPriorityAttackRangeTarget;

        /// <summary>
        /// 是否优先攻击空中目标
        /// </summary>
        public readonly bool isPriorityAttackAirTarget;

        public const int Id = -1261486268;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "radius:" + radius + ","
            + "height:" + height + ","
            + "moveSpeed:" + moveSpeed + ","
            + "detectRadius:" + detectRadius + ","
            + "attackRadius:" + attackRadius + ","
            + "isPriorityAttackRangeTarget:" + isPriorityAttackRangeTarget + ","
            + "isPriorityAttackAirTarget:" + isPriorityAttackAirTarget + ","
            + "}";
        }

        partial void PostInit();
    }
}
