
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum QualityType
    {
        /// <summary>
        /// 最差品质
        /// </summary>
        White = 1,

        /// <summary>
        /// 蓝色的
        /// </summary>
        Blue = 2,

        /// <summary>
        /// 紫色的
        /// </summary>
        Purple = 3,

        /// <summary>
        /// 最高品质
        /// </summary>
        Red = 4,

    }
}
