
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class ResourceConfig : BeanBase
    {
        public ResourceConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            assetUrl = buf.ReadString();

            PostInit();
        }

        public static ResourceConfig DeserializeResourceConfig(ByteBuf buf)
        {
            return new ResourceConfig(buf);
        }

        /// <summary>
        /// 资源ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 资源地址
        /// </summary>
        public readonly string assetUrl;

        public const int Id = -1505018608;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "assetUrl:" + assetUrl + ","
            + "}";
        }

        partial void PostInit();
    }
}
