
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum SettleType
    {
        /// <summary>
        /// 挑战
        /// </summary>
        Challenge = 0,

        /// <summary>
        /// 通关
        /// </summary>
        Pass = 1,

    }
}
