
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class SkillConfig : BeanBase
    {
        public SkillConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            name = buf.ReadString();
            type = buf.ReadInt();
            subtype = buf.ReadInt();
            coolingTime = buf.ReadInt();
            detectRadius = buf.ReadFloat();
            damageRadius = buf.ReadFloat();
            onGroundAttack = buf.ReadBool();
            onAirStrike = buf.ReadBool();
            isRangeAttack = buf.ReadBool();
            punctureCount = buf.ReadInt();
            iconId = buf.ReadInt();
            soundId = buf.ReadInt();
            hitSoundId = buf.ReadInt();
            hitEffectId = buf.ReadInt();

            PostInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf buf)
        {
            return new SkillConfig(buf);
        }

        /// <summary>
        /// 技能ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string name;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly int type;

        /// <summary>
        /// 二级类型
        /// </summary>
        public readonly int subtype;

        /// <summary>
        /// 冷却时间
        /// </summary>
        public readonly int coolingTime;

        /// <summary>
        /// 攻击检测半径
        /// </summary>
        public readonly float detectRadius;

        /// <summary>
        /// 伤害半径
        /// </summary>
        public readonly float damageRadius;

        /// <summary>
        /// 地面攻击
        /// </summary>
        public readonly bool onGroundAttack;

        /// <summary>
        /// 空中打击
        /// </summary>
        public readonly bool onAirStrike;

        /// <summary>
        /// 是否为远程攻击
        /// </summary>
        public readonly bool isRangeAttack;

        /// <summary>
        /// 穿透攻击次数
        /// </summary>
        public readonly int punctureCount;

        /// <summary>
        /// 图标资源ID
        /// </summary>
        public readonly int iconId;

        /// <summary>
        /// 音效资源ID
        /// </summary>
        public readonly int soundId;

        /// <summary>
        /// 命中音效资源ID
        /// </summary>
        public readonly int hitSoundId;

        /// <summary>
        /// 命中特效资源ID
        /// </summary>
        public readonly int hitEffectId;

        public const int Id = -844226349;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "name:" + name + ","
            + "type:" + type + ","
            + "subtype:" + subtype + ","
            + "coolingTime:" + coolingTime + ","
            + "detectRadius:" + detectRadius + ","
            + "damageRadius:" + damageRadius + ","
            + "onGroundAttack:" + onGroundAttack + ","
            + "onAirStrike:" + onAirStrike + ","
            + "isRangeAttack:" + isRangeAttack + ","
            + "punctureCount:" + punctureCount + ","
            + "iconId:" + iconId + ","
            + "soundId:" + soundId + ","
            + "hitSoundId:" + hitSoundId + ","
            + "hitEffectId:" + hitEffectId + ","
            + "}";
        }

        partial void PostInit();
    }
}
