
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
    public sealed partial class SoundConfig : BeanBase
    {
        public SoundConfig(ByteBuf buf)
        {
            id = buf.ReadInt();
            resourceId = buf.ReadInt();
            animInterrupted = buf.ReadBool();

            PostInit();
        }

        public static SoundConfig DeserializeSoundConfig(ByteBuf buf)
        {
            return new SoundConfig(buf);
        }

        /// <summary>
        /// 音频ID
        /// </summary>
        public readonly int id;

        /// <summary>
        /// 资源ID
        /// </summary>
        public readonly int resourceId;

        /// <summary>
        /// 动画中断标识
        /// </summary>
        public readonly bool animInterrupted;

        public const int Id = -1164338927;

        public override int GetTypeId() => Id;

        public override string ToString()
        {
            return "{ "
            + "id:" + id + ","
            + "resourceId:" + resourceId + ","
            + "animInterrupted:" + animInterrupted + ","
            + "}";
        }

        partial void PostInit();
    }
}
