
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class AvatarLevelConfigTable : ConfigSingleton<AvatarLevelConfigTable>
    {
        private readonly List<AvatarLevelConfig> _dataList;
        private readonly Dictionary<int, AvatarLevelConfig> _dataMap;

        public AvatarLevelConfigTable(ByteBuf buf)
        {
            _dataList = new List<AvatarLevelConfig>();
            _dataMap = new Dictionary<int, AvatarLevelConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                AvatarLevelConfig v;
                v = AvatarLevelConfig.DeserializeAvatarLevelConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<AvatarLevelConfig> DataList => _dataList;

        public Dictionary<int, AvatarLevelConfig> DataMap => _dataMap;

        public AvatarLevelConfig Get(int key) => _dataMap[key];

        public AvatarLevelConfig this[int key] => _dataMap[key];

        public AvatarLevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
