
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class BulletConfigTable : ConfigSingleton<BulletConfigTable>
    {
        private readonly List<BulletConfig> _dataList;
        private readonly Dictionary<int, BulletConfig> _dataMap;

        public BulletConfigTable(ByteBuf buf)
        {
            _dataList = new List<BulletConfig>();
            _dataMap = new Dictionary<int, BulletConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                BulletConfig v;
                v = BulletConfig.DeserializeBulletConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<BulletConfig> DataList => _dataList;

        public Dictionary<int, BulletConfig> DataMap => _dataMap;

        public BulletConfig Get(int key) => _dataMap[key];

        public BulletConfig this[int key] => _dataMap[key];

        public BulletConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
