
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class EffectConfigTable : ConfigSingleton<EffectConfigTable>
    {
        private readonly List<EffectConfig> _dataList;
        private readonly Dictionary<int, EffectConfig> _dataMap;

        public EffectConfigTable(ByteBuf buf)
        {
            _dataList = new List<EffectConfig>();
            _dataMap = new Dictionary<int, EffectConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                EffectConfig v;
                v = EffectConfig.DeserializeEffectConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<EffectConfig> DataList => _dataList;

        public Dictionary<int, EffectConfig> DataMap => _dataMap;

        public EffectConfig Get(int key) => _dataMap[key];

        public EffectConfig this[int key] => _dataMap[key];

        public EffectConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
