
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class FuncOpenConfigTable : ConfigSingleton<FuncOpenConfigTable>
    {
        private readonly List<FuncOpenConfig> _dataList;
        private readonly Dictionary<int, FuncOpenConfig> _dataMap;

        public FuncOpenConfigTable(ByteBuf buf)
        {
            _dataList = new List<FuncOpenConfig>();
            _dataMap = new Dictionary<int, FuncOpenConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                FuncOpenConfig v;
                v = FuncOpenConfig.DeserializeFuncOpenConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<FuncOpenConfig> DataList => _dataList;

        public Dictionary<int, FuncOpenConfig> DataMap => _dataMap;

        public FuncOpenConfig Get(int key) => _dataMap[key];

        public FuncOpenConfig this[int key] => _dataMap[key];

        public FuncOpenConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
