
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class FuncConditionConfigTable : ConfigSingleton<FuncConditionConfigTable>
    {
        private readonly List<FuncConditionConfig> _dataList;
        private readonly Dictionary<int, FuncConditionConfig> _dataMap;

        public FuncConditionConfigTable(ByteBuf buf)
        {
            _dataList = new List<FuncConditionConfig>();
            _dataMap = new Dictionary<int, FuncConditionConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                FuncConditionConfig v;
                v = FuncConditionConfig.DeserializeFuncConditionConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<FuncConditionConfig> DataList => _dataList;

        public Dictionary<int, FuncConditionConfig> DataMap => _dataMap;

        public FuncConditionConfig Get(int key) => _dataMap[key];

        public FuncConditionConfig this[int key] => _dataMap[key];

        public FuncConditionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
