
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class HouseFashionConfigTable : ConfigSingleton<HouseFashionConfigTable>
    {
        private readonly List<HouseFashionConfig> _dataList;
        private readonly Dictionary<int, HouseFashionConfig> _dataMap;

        public HouseFashionConfigTable(ByteBuf buf)
        {
            _dataList = new List<HouseFashionConfig>();
            _dataMap = new Dictionary<int, HouseFashionConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                HouseFashionConfig v;
                v = HouseFashionConfig.DeserializeHouseFashionConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<HouseFashionConfig> DataList => _dataList;

        public Dictionary<int, HouseFashionConfig> DataMap => _dataMap;

        public HouseFashionConfig Get(int key) => _dataMap[key];

        public HouseFashionConfig this[int key] => _dataMap[key];

        public HouseFashionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
