
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class HouseAttrConfigTable : ConfigSingleton<HouseAttrConfigTable>
    {
        private readonly List<HouseAttrConfig> _dataList;
        private readonly Dictionary<int, HouseAttrConfig> _dataMap;

        public HouseAttrConfigTable(ByteBuf buf)
        {
            _dataList = new List<HouseAttrConfig>();
            _dataMap = new Dictionary<int, HouseAttrConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                HouseAttrConfig v;
                v = HouseAttrConfig.DeserializeHouseAttrConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<HouseAttrConfig> DataList => _dataList;

        public Dictionary<int, HouseAttrConfig> DataMap => _dataMap;

        public HouseAttrConfig Get(int key) => _dataMap[key];

        public HouseAttrConfig this[int key] => _dataMap[key];

        public HouseAttrConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
