
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class ItemConfigTable : ConfigSingleton<ItemConfigTable>
    {
        private readonly List<ItemConfig> _dataList;
        private readonly Dictionary<int, ItemConfig> _dataMap;

        public ItemConfigTable(ByteBuf buf)
        {
            _dataList = new List<ItemConfig>();
            _dataMap = new Dictionary<int, ItemConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                ItemConfig v;
                v = ItemConfig.DeserializeItemConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<ItemConfig> DataList => _dataList;

        public Dictionary<int, ItemConfig> DataMap => _dataMap;

        public ItemConfig Get(int key) => _dataMap[key];

        public ItemConfig this[int key] => _dataMap[key];

        public ItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
