
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class MainLevelConfigTable : ConfigSingleton<MainLevelConfigTable>
    {
        private readonly List<MainLevelConfig> _dataList;
        private readonly Dictionary<int, MainLevelConfig> _dataMap;

        public MainLevelConfigTable(ByteBuf buf)
        {
            _dataList = new List<MainLevelConfig>();
            _dataMap = new Dictionary<int, MainLevelConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                MainLevelConfig v;
                v = MainLevelConfig.DeserializeMainLevelConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<MainLevelConfig> DataList => _dataList;

        public Dictionary<int, MainLevelConfig> DataMap => _dataMap;

        public MainLevelConfig Get(int key) => _dataMap[key];

        public MainLevelConfig this[int key] => _dataMap[key];

        public MainLevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
