
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class MailConfigTable : ConfigSingleton<MailConfigTable>
    {
        private readonly List<MailConfig> _dataList;
        private readonly Dictionary<int, MailConfig> _dataMap;

        public MailConfigTable(ByteBuf buf)
        {
            _dataList = new List<MailConfig>();
            _dataMap = new Dictionary<int, MailConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                MailConfig v;
                v = MailConfig.DeserializeMailConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<MailConfig> DataList => _dataList;

        public Dictionary<int, MailConfig> DataMap => _dataMap;

        public MailConfig Get(int key) => _dataMap[key];

        public MailConfig this[int key] => _dataMap[key];

        public MailConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
