
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class MonsterConfigTable : ConfigSingleton<MonsterConfigTable>
    {
        private readonly List<MonsterConfig> _dataList;
        private readonly Dictionary<int, MonsterConfig> _dataMap;

        public MonsterConfigTable(ByteBuf buf)
        {
            _dataList = new List<MonsterConfig>();
            _dataMap = new Dictionary<int, MonsterConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                MonsterConfig v;
                v = MonsterConfig.DeserializeMonsterConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<MonsterConfig> DataList => _dataList;

        public Dictionary<int, MonsterConfig> DataMap => _dataMap;

        public MonsterConfig Get(int key) => _dataMap[key];

        public MonsterConfig this[int key] => _dataMap[key];

        public MonsterConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
