
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class MonsterAttrConfigTable : ConfigSingleton<MonsterAttrConfigTable>
    {
        private readonly List<MonsterAttrConfig> _dataList;
        private readonly Dictionary<int, MonsterAttrConfig> _dataMap;

        public MonsterAttrConfigTable(ByteBuf buf)
        {
            _dataList = new List<MonsterAttrConfig>();
            _dataMap = new Dictionary<int, MonsterAttrConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                MonsterAttrConfig v;
                v = MonsterAttrConfig.DeserializeMonsterAttrConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<MonsterAttrConfig> DataList => _dataList;

        public Dictionary<int, MonsterAttrConfig> DataMap => _dataMap;

        public MonsterAttrConfig Get(int key) => _dataMap[key];

        public MonsterAttrConfig this[int key] => _dataMap[key];

        public MonsterAttrConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
