
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class MonsterAIConfigTable : ConfigSingleton<MonsterAIConfigTable>
    {
        private readonly List<MonsterAIConfig> _dataList;
        private readonly Dictionary<int, MonsterAIConfig> _dataMap;

        public MonsterAIConfigTable(ByteBuf buf)
        {
            _dataList = new List<MonsterAIConfig>();
            _dataMap = new Dictionary<int, MonsterAIConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                MonsterAIConfig v;
                v = MonsterAIConfig.DeserializeMonsterAIConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<MonsterAIConfig> DataList => _dataList;

        public Dictionary<int, MonsterAIConfig> DataMap => _dataMap;

        public MonsterAIConfig Get(int key) => _dataMap[key];

        public MonsterAIConfig this[int key] => _dataMap[key];

        public MonsterAIConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
