
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class SkillConfigTable : ConfigSingleton<SkillConfigTable>
    {
        private readonly List<SkillConfig> _dataList;
        private readonly Dictionary<int, SkillConfig> _dataMap;

        public SkillConfigTable(ByteBuf buf)
        {
            _dataList = new List<SkillConfig>();
            _dataMap = new Dictionary<int, SkillConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                SkillConfig v;
                v = SkillConfig.DeserializeSkillConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<SkillConfig> DataList => _dataList;

        public Dictionary<int, SkillConfig> DataMap => _dataMap;

        public SkillConfig Get(int key) => _dataMap[key];

        public SkillConfig this[int key] => _dataMap[key];

        public SkillConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
