
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class SoldierAIConfigTable : ConfigSingleton<SoldierAIConfigTable>
    {
        private readonly List<SoldierAIConfig> _dataList;
        private readonly Dictionary<int, SoldierAIConfig> _dataMap;

        public SoldierAIConfigTable(ByteBuf buf)
        {
            _dataList = new List<SoldierAIConfig>();
            _dataMap = new Dictionary<int, SoldierAIConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                SoldierAIConfig v;
                v = SoldierAIConfig.DeserializeSoldierAIConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<SoldierAIConfig> DataList => _dataList;

        public Dictionary<int, SoldierAIConfig> DataMap => _dataMap;

        public SoldierAIConfig Get(int key) => _dataMap[key];

        public SoldierAIConfig this[int key] => _dataMap[key];

        public SoldierAIConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
