
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace Game.Config
{
    [Config]
    public partial class SoldierAttrConfigTable : ConfigSingleton<SoldierAttrConfigTable>
    {
        private readonly List<SoldierAttrConfig> _dataList;
        private readonly Dictionary<int, SoldierAttrConfig> _dataMap;

        public SoldierAttrConfigTable(ByteBuf buf)
        {
            _dataList = new List<SoldierAttrConfig>();
            _dataMap = new Dictionary<int, SoldierAttrConfig>();

            for (int n = buf.ReadSize(); n > 0; --n)
            {
                SoldierAttrConfig v;
                v = SoldierAttrConfig.DeserializeSoldierAttrConfig(buf);
                _dataList.Add(v);
                _dataMap.Add(v.id, v);
            }

            PostInit();
        }

        public List<SoldierAttrConfig> DataList => _dataList;

        public Dictionary<int, SoldierAttrConfig> DataMap => _dataMap;

        public SoldierAttrConfig Get(int key) => _dataMap[key];

        public SoldierAttrConfig this[int key] => _dataMap[key];

        public SoldierAttrConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        partial void PostInit();
    }
}
