
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum TinyTimeStatus
    {
        /// <summary>
        /// 白天
        /// </summary>
        Day = 0,

        /// <summary>
        /// 黑夜
        /// </summary>
        Night = 1,

    }
}
