
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Config
{
    public enum UseType
    {
        /// <summary>
        /// 无
        /// </summary>
        Common = 0,

        /// <summary>
        /// 手动
        /// </summary>
        Manual = 1,

        /// <summary>
        /// 自动
        /// </summary>
        Auto = 2,

    }
}
